#pragma once                              // Ensure the header is included only once during compilation.

#include <QtWidgets/QMainWindow>          // Include the QMainWindow class, which provides a main application window.
#include "ui_QtLibGUI.h"                  // Include the UI class for your main window. This is generated by the Qt UIC (User Interface Compiler) from your .ui file.

class QtLibGUI : public QMainWindow       // Your main window class derived from QMainWindow.
{
    Q_OBJECT                              // This macro is required in any class that uses Qt's signals and slots mechanism.

public:
    QtLibGUI(QWidget* parent = nullptr);  // Constructor. Takes an optional parent widget.
    ~QtLibGUI();                          // Destructor.

private:
    Ui::QtLibGUIClass ui;                 // An instance of the UI class. This provides access to all the widgets you design in the .ui file.
    void onAddBookButtonClicked();
};
