#include "QtLibGUI.h"
#include "qpushbutton.h"
#include "qlineedit.h"
#include "qtextedit.h"

// Constructor
QtLibGUI::QtLibGUI(QWidget* parent)
    : QMainWindow(parent)
{
    ui.setupUi(this);               // This method is auto-generated by the UIC (User Interface Compiler) and sets up all the widgets and layouts as defined in the .ui file.
    connect(ui.AddBookButton, &QPushButton::clicked, this, &QtLibGUI::onAddBookButtonClicked);
}

// Currently, the destructor empty, but you can add cleanup code here if needed in the future.
QtLibGUI::~QtLibGUI()
{}

void QtLibGUI::onAddBookButtonClicked() {
    QString booktitle = ui.lineEdit->text();
    ui.textEdit->setText(booktitle);
}