#include "QtLibGUI.h"
#include "qpushbutton.h"
#include "qlineedit.h"
#include "qtextedit.h"


// Constructor
QtLibGUI::QtLibGUI(CustomClient* client, QWidget* parent) : QMainWindow(parent), myClient(client)
{
    ui.setupUi(this);               // This method is auto-generated by the UIC (User Interface Compiler) and sets up all the widgets and layouts as defined in the .ui file.

    connect(ui.addBookButton, &QPushButton::clicked, this, &QtLibGUI::onAddBookButtonClicked);
    connect(ui.sendMessageButton, &QPushButton::clicked, this, &QtLibGUI::onSendMessage);
    connect(ui.listBooksButton, &QPushButton::clicked, this, &QtLibGUI::onListBooks);
    connect(ui.listMembersButton, &QPushButton::clicked, this, &QtLibGUI::onListMembers);
    connect(ui.addMemberButton, &QPushButton::clicked, this, &QtLibGUI::onAddMember);

    connect(&getMsgTimer, &QTimer::timeout, this, &QtLibGUI::onGetMessage);

    getMsgTimer.setInterval(1000); // in milliseconds.
    getMsgTimer.start();
}

// Currently, the destructor empty, but you can add cleanup code here if needed in the future.
QtLibGUI::~QtLibGUI()
{}

void QtLibGUI::onListBooks() {
    myClient->listBooks();
}

void QtLibGUI::onListMembers() {
    myClient->listMembers();
}

void QtLibGUI::onSendMessage() {
    QString tempMsgToSend = ui.lineEdit->text();
    std::string msgToSend = tempMsgToSend.toStdString();
    myClient->MessageServer(msgToSend);
    ui.textEdit->append("Message sent");
}

void QtLibGUI::onGetMessage() {
    std::string tempResponse = myClient->getMessage();
    if (!tempResponse.empty()) {
        QString response = QString::fromStdString(tempResponse);
        ui.textEdit->append(response);
    }
}

void QtLibGUI::onAddBookButtonClicked() {
    QString tempBookTitle = ui.bookTitleInput->text();
    QString tempAuthor = ui.authorInput->text();
    QString tempGenre = ui.genreInput->text();
    QString tempPublicationYear = ui.publicationYearInput->text();
    QString tempIsbn = ui.isbnAddBookInput->text();
    
    QString tempMsgToSend = tempBookTitle + ";" + tempAuthor + ";" + tempGenre + ";" +
        tempIsbn + ";" + tempPublicationYear + ";";

    std::string msgToSendString = tempMsgToSend.toStdString();
    myClient->addBookCommand(msgToSendString);
}

void QtLibGUI::onAddMember() {
    std::string name = ui.nameInput->text().toStdString();
    std::string ID = ui.newIDInput->text().toStdString();
    std::string username = ui.newUsernameInput->text().toStdString();
    std::string password = ui.newPasswordInput->text().toStdString();
    std::string msgToSend = name + ";" + ID + ";" + username + ";" + password + ";";
    myClient->addMemberCommand(msgToSend);
}
